lib/modules/subscribe_button/widget.php

cf. http://codex.wordpress.org/Function_Reference/register_sidebar and e.g. http://wordpress.stackexchange.com/questions/18942/add-class-to-before-widget-from-within-a-custom-widget

Add {before,after}_widget data to widgets.

---

lib/modules/twitter_summary_card/twitter_summary_card.php

The old twitter cards whitelist application form was replaced by the card validator, where you can request your WP site to be whitelisted.

Old application system replaced

---

bower.json
composer.lock

bower dependencies can now be installed with `bower install`.
The latest version of podlove-web-player v3 will be installed and can be updated with `bower update`, too.
Update composer.lock, because it causes trouble on initial install.

Bower.json and composer.lock

---

lib/feed_discoverability.php

Change \PODLOVE\PLUGIN_DIR constant to \Podlove\PLUGIN_DIR in lib/feed_discoverability.php to fix following error: Fatal error: Undefined constant 'PODLOVE\\PLUGIN_DIR'
This happens with Debian GNU/Linux 8.0 (jessie) (3.16.0-4-amd64) and HipHop VM 3.7.0

Fix case sensitive constant

---

lib/modules/podlove_web_player/player_v3/player_config.php

This makes the webplayer 3 configuration ready for internationalization. Tested with `multilingual` branch of podlove-web-player.

Prepare podlove webplayer configuration for internationalization

---

lib/modules/widgets/widgets/recent_episodes.php

`post_permalink()` appears deprecated and might cause a Wordpress-notice within the `<a>`-Tag:
```HTML
<a href="<br />
<b>Notice</b>:  post_permalink ist seit Version 4.4.0 <strong>veraltet</strong>!
[…]
>
```
https://developer.wordpress.org/reference/functions/post_permalink/

updated deprecated post_permalink() to newer get_permalink()

---

lib/modules/networks/networks.php
lib/settings/support.php
lib/system_report.php

* Changed the system report messages for multisite environments to match the current plugin infrastructure
* Changed the checks performed to determine issues with the network environment
* Instead of an error a notice is displayed in the system report if the Publisher is not active in the main WP blog
* Fixes a bug that showed the placeholder (%s) instead of the number of errors/notices in the system report

Optimizing Network (Multisite) System Report

---

includes/permalinks.php

_usort_terms_by_ID is deprecated and produces a notice. 
`Notice: _usort_terms_by_ID ist seit Version 4.7.0 veraltet! Benutze stattdessen wp_list_sort(). in /mnt/web203/d1/18/53783218/htdocs/lieblings-plaetzchen.com/wp-includes/functions.php on line 3853`
When selecting multuple categories for an episode, these notices will be visible multiple times in the backend and frontend. This PR fixes that while ensuring backwards compatibility.

Fixed depreation warning when using multiple categories

---

lib/helper.php
lib/modules/podlove_web_player/player_v4/html5printer.php
lib/modules/podlove_web_player/player_v4/module.php

In order to customize the appearance of the v4 player in the publishing plugin I added a form field to select which components are visible in the player embed. I also updated the default values for the primary and secondary color to pull from the configured theme settings.

Adding ability to specify visible components in v4 player

---

includes/downloads.php

Use X-Real-IP or X-Forwarded-For over REMOTE_ADDR for web servers that are behind a reverse proxy
Otherwise it will use the reverse proxy IP address for both the request id as well as for Geo IP lookup. Both will yield unexpected results when using the reverse proxy address.

[tracking] Correctly handle IP address for web servers with reverse proxies

---

lib/modules/podlove_web_player/player_v4/pwp4.js

If the function is undefined (for example in IE11), it may cause problems with other scripts.  
For example, on our site the [a3 Lazy Load plugin](https://wordpress.org/plugins/a3-lazy-load/) ceased working if podlove was embedded on a page.  
Sadly around 25% of our users use Internet Explorer 11, so this affected a large part of our user base.

Check if podlovePlayer is defined

---

includes/downloads.php
lib/settings/expert/tab/tracking.php

These commits add support for Google Analytics.
A Google Analytics tracking ID can be set from the Podlove Publisher tracking settings.
If provided, Podlove Publisher will forward available tracking data to Google Analytics.

Add Google Analytics support

---

includes/episode_number_column.php
includes/episode_number_quick_edit_form.php
plugin.php

Addresses https://community.podlove.org/t/feature-request-quick-edit-fields-in-episode-table/1911
Disclaimer: This solution works but is kinda hacky (use of str_replace()) and might easily break for future WordPress updates.

Adds a quickedit menu to the episode table

---

lib/modules/transcripts/template/group.php
lib/modules/transcripts/template_extensions.php

For the case where a contributor object does not exist but the user wants to use the name of the speaker in the context of the transcript template.

Exposed voice attribute to transcript templates

---

css/admin.css
lib/downloads_list_table.php

There were a problem with the download list descriptions on mobile view:
I was able to fix it with some css:

Fixed download list description in analytics on mobile

---

js/src/analytics/totals.js
lib/settings/analytics.php

I've made a prototype to chart the table of downloads. If you say that all your subscribers are downloading your episodes automatically within the first 24/48 hours, then you can interpret the chart as history of number of subscribers.
Here is an example (with removed numbers):
There are a lot of bugs, missing things and shortcuts. I'm posting this to get some feedback and to check that I don't make something complete wrong.

Table of downloads as linechart / history of subscriptions

---

lib/model/podcast.php
lib/settings/dashboard/file_validation.php
views/settings/dashboard/file_validation.php

In our podcast one person adds the blog post and the other person does the audio post production. At the end both must get together. To verify this, you can use the validate podcast files on the dashboard. But at the moment drafts and future posts are missing. I think that's a bug, because this line indicates me, that they should be included:
https://github.com/podlove/podlove-publisher/blob/50c06f587bb3a37fe5f91221804734d79c12971b/lib/settings/dashboard/file_validation.php#L26
The problem is, that the template iterates thru $episodes and there the draft and future posts are not included. I fixed this.
If you look at the picture:
* eb034 is a draft, scheduled in the far future, missing media files
* eb033 is a draft, missing media file slug
* eb032 is scheduled, missing media files
* …

Added all relevant post status to validate podcast files

---

includes/cover_art.php
lib/feeds/base.php
lib/modules/shownotes/shownotes.php
lib/modules/shows/shows.php

fix: various cover art url encoding issues
- do not sanitize episode image url (because it breaks special characters)
- use esc_attr instead of htmlentities for output sanitization
- apply same logic for shows image tag

fix: coverart url encoding

---

bootstrap/constants.php

_Resolves Issue #1194_
When collecting parsed plugin metadata from WordPress using `get_plugin_data`, translations and markup are not disabled by default. This causes WordPress to indirectly call `wptexturize`, thus breaking other plugins and translations. 
About the indirect `wptexturize` call from `get_plugin_data()`, see [this comment in the Wordpress Docs](https://developer.wordpress.org/reference/functions/get_plugin_data/#comment-2109). 
The WordPress docs say [this about `wptexturize`](https://developer.wordpress.org/reference/functions/wptexturize/):
> Do not use this function before the ‘init’ action hook; everything will break.
I propose the following change:
Call the `get_plugin_data()` method with additional parameters disabling translations and markup. This avoids calling …

#1194 Avoid indirectly calling wptexturize too early

---

lib/model/episode.php

The new version proposed on WordPress plugin shop is bugged (totally inusable):
Creation of episodes is NOT possible (no saving datas, and no recognization of podcast files),
Caused by a bad creation a tables at installation.
This pull request fix that, correcting a ")" absent in VARCHAR sql declaration.

Major fix bug at install causing by bad episodes table creation.

---

lib/modules/contributors/templates/podcast-contributor-table.twig

Ich habe die Optionen avatars, groups und roles beim shortcode podlove-episode-contributor-list eingebaut. 
Aus meiner Sicht macht die Option title in der neuen Darstellung keinen Sinn mehr.
Für den shortcode podlove-podcast-contributor-list fehlt noch die Dokumentation. Die Option avatars könnte eingebaut werden. Bei den Optionen groups und roles bin ich mir nicht sicher.

(fixed) Github issue #1233

---

lib/feeds.php

A warning is triggered by PHP if `$_SERVER['HTTP_USER_AGENT']` is not set.
This commit fixes this by using the null-coalescing operator to provide a sane default (empty string).
Also two occurrences of `isset($array[$key]) && $array[$key]` are simplified by using the null-coalescing operator.
In addition to it, two string comparisons where converted from `==` to `===`.

Fix for PHP Warning "undefined array key"

---

lib/podcast_post_type.php

The filter `get_the_excerpt` can use the `$post` parameter instead of the global variable.
To fix #1372

Fix (episode summary): use filter parameter instead of global $post

---

client/src/modules/mediafiles/MediaFiles.vue
client/src/modules/mediafiles/components/AssetsTable.vue
client/src/modules/mediafiles/components/MediaUpload.vue
client/src/sagas/chapters.sagas.ts
client/src/sagas/episode.sagas.ts
client/src/sagas/mediafiles.sagas.ts
client/src/sagas/wordpress.sagas.ts
client/src/store/episode.store.ts
client/src/store/mediafiles.store.ts
client/src/store/selectors.ts
client/src/store/settings.store.ts
client/src/store/wordpress.store.ts
includes/podlove_data_js_adapter.php
lib/modules/wordpress_file_upload/wordpress_file_upload.php

Continuation of #1368
Some tweaks that made it feel snappy:
- added a "quicksave" event so I can trigger episode save without waiting for the debounce
- display verification indicator
- auto-enable asset on verification
Also I'm hiding the slug input in upload mode because I think it's not necessary here.
https://github.com/podlove/podlove-publisher/assets/235918/6e6e9509-e864-4792-a4bd-94bcdfcf17c7

Feature: MediaFile Upload to WordPress

---

client/src/sagas/contributors.sagas.ts
lib/modules/contributors/views/form_table.php

If the list of roles and groups for the contributors is not empty, the first entry must be selected.
The old contributors view is still needed for the contributors defaults UI.

fix(contributors) - fix #1386

---

lib/settings/support.php

Commit a722d451b99dc3c2a160079e40dc23e4b2063632 inadvertantly removed the format specifier, causing the support page to crash due to unknown format specifier `%M`.
This PR restores the format specifier.

fix: format specifier

---

lib/file_type_list_table.php
lib/settings/file_type.php
readme.txt

Follwing a discussion on Discord (https://discord.com/channels/726154142980243459/898908411356393552/1166796792025858078), here's the suggestion to make file types readonly. It's a pre requirement for us eventually doing more with them (adding mime type and other metadata) and presumably affects less than a hand full of people.

Make File Types readonly

---

client/src/sagas/contributors.sagas.ts

If the list of roles and groups for the contributors is not empty, the first entry must be selected. The first entry don't have always ID 1. Use the Id from the first entry in the list.

fix(contributor) - Set group for episode contributor

---

Makefile

by simply using `make composer_with_prefixing` instead of the old, inaccurate copy pasted version of it.
Specifically fixes an incompatibility with woocommerce.

fix(build): delete all vendor prefixed directories

---

lib/feeds/base.php

This commit fixes "deprecated" notices which are thrown for each episode in the feed when certain fields are empty (`null`):
```
PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /app/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/feeds/base.php on line 13
PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /app/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/feeds/base.php on line 14
```
Also removes one branch from the condition which fills `$description`.

Ensure `trim()` is called with correct argument type.

---

lib/modules/contributors/rest_api.php

An optional method argument should not be followed by required argument. There's no need to specify a default value for `$result` as the empty array `[]` is provided as initial value for `array_reduce()` already.
```
PHP Deprecated:  Optional parameter $result declared before required parameter $contributor is implicitly treated as a required parameter in podlove-podcasting-plugin-for-wordpress/lib/modules/contributors/rest_api.php on line 76
```
(also removed two trailing whitespaces)

fix "deprecated" message

---

includes/explicit_content.php
includes/license.php

Dieser Commit löst das Problem (https://community.podlove.org/t/license-and-explicit-warning-are-not-saved/3311) 
Beim Speichern der Episoden-Seite wurde die Lizenz und das Explicit-Flag überschrieben.

fix(episode) - Remove old save code for license and explicit

---

composer.json
composer.lock
lib/custom_guid.php

Based on https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/other-recommendations.md#episode-guid
Notable difference: uses uuid4 (random) instead of uuid5 (based on enclosure url). That would require much more rework, mainly generating the guid on post publication instead of on post creation, because currently the enclosure url is not defined on post creation. We also need to deal with the fact that we have multiple assets and need to define which one is the main asset so we know which url to pick.

change: episode guid generation

---

lib/modules/onboarding/css/podlove-onboarding-banner.css
lib/modules/onboarding/onboarding.php

Ich habe mir das CSS vom Wordpress Welcome Banner als Basis genommen und auf unser Banner angewendet. Damit sollten die Probleme mit der Darstellung von Admin-Seiten die höher als eine Bildschirmseite sind behoben sein.

fix - height issue with onboarding banner

---

composer.json
composer.lock
includes/api/podcast.php
includes/setup.php
lib/feeds/base.php
lib/model/podcast.php
lib/version.php

Following specification: https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#guid
- outputs `podcast:guid` tag in RSS feed if there is a value
- during plugin setup, a guid is generated
- adds database migration that generates a guid if there is none
- extends REST api to read and write the podcast guid

Feature: `podcast:guid`

---

.dockerignore
.github/workflows/docker-image.yml
Dockerfile
bin/docker-entry.sh
bin/docker-setup.sh
docker-compose.yml

- creates a docker image (`ghcr.io/podlove/podlove-publisher:[beta|master]`) on each push to master or beta
- docker image will create a wordpress instance with a user (admin:admin) and the publisher preinstalled and activated

ci: publish docker images for branches

---

lib/modules/onboarding/onboarding.php
lib/modules/onboarding/rest_api.php

Ich habe einen API Endpunkt angelegt mit dem während des Onboardings die nötigen Einstellungen vorgenommen werden können. Aktuell wird nur das File Upload Modul aktiviert und ein default Verzeichnis gesetzt. Beim Import sollte falls nötig noch das Transcript- und Contributor-Modul aktiviert werden.

feat(onboarding) - Set default settings

---

includes/api/episodes.php

Bei der Bestückung der Episoden-Daten für die GET route, gab es einen Itemsnamen Fehler.

fix(api) - Episode cover typing error

---

client/src/store/episode.store.ts
includes/api/episodes.php

Fix #1490 
PR #1464 was not enough. Explicit item was net set and in the RestAPI was a type mismatch.

fix(episode) - expicit tag was not stored
