- lib/modules/contributors/templates/_contributor-table-row.twig
- lib/modules/contributors/templates/contributor-comma-separated.twig
- lib/modules/contributors/templates/contributor-list.twig
- lib/modules/contributors/templates/podcast-contributor-list.twig
> Use new contributor image object for avatar display

- lib/ajax/ajax.php
- lib/ajax/template_controller.php
Only users with the correct permissions should be able to edit templates and read analytics.
> Check permissions in AJAX-calls

- lib/modules/contributors/settings/tab/contributors.php
> Changes description of Public name

- js/src/admin.js
Provides a fix for #817 (we need more spaghetti code!)
> Encode URL scheme only if not already encoded

- lib/modules/flattr/podcast_flattr_settings_tab.php
- lib/modules/social/data/services.yml
see https://podlove.slack.com/archives/C02UDTVQZ/p1492259876518909
> harmonise Flattr terminology

- lib/modules/contributors/contributor_list_table.php
- lib/modules/contributors/settings/tab/contributors.php
* Fixes a bug that prevented sorting Contributors by their contribution count in the admin interface
* Fixes an issue that results in PHP Notices when creating a new contributor
> Contributor Bugfixes

- lib/system_report.php
* Added WP DB Charset & Collation variables to System Report
* Added a routine to check if the episode table has an UTF-8 charset
This PR will help to debug charset-related issues.
> Add Charset/Collation Check to sys report

- lib/modules/title_migration/title_migration.php
Can now also convert post titles following the following specification:
```
<prefix><episode-number>: <title>
```
> Added colon to title separation list.

- bootstrap/bootstrap.php
This solves and closes #1003
Thanks for considering.
> use fullpath to require autoload and constant

- lib/helper.php
- lib/modules/podlove_web_player/player_v4/html5printer.php
- lib/modules/podlove_web_player/player_v4/module.php
... instead of the language defined by the browser locale
Renewal of #955
> Add option to the player_v4 module to choose the podcast language

- css/admin.css
- js/admin/template.js
- lib/settings/feed.php
- lib/settings/templates.php
> Template UI fix

- lib/modules/seasons/seasons.php
> Fix season order arg

- .build/docker-compose.yaml
- .build/uploads.ini
- Makefile
- yarn.lock
chore(dev): use docker for build and dev environment
> use docker for build and dev env

- includes/episode_number_quick_edit_form.php
- lib/form/input/builder.php
- lib/podcast_post_meta_box.php
Only allow episode numbers of 0 and higher in the episode metabox and on the quick edit.
> podcast-episode-number | only allow episode numbers of 0 and higher

- includes/api/api.php
- includes/api/podcast.php
Hier ist ein erster Commit zur Bereitstellung aller Infos per Rest-API
> feat(api): implement podcast rest api controller

- js/src/admin/episode_duration.js
Hi Eric. Wie besprochen unser kleiner Change für den duration check. Danke!
> added mp4 to asset duration check

- podlove.php
> Fix PHP version in error message

- client/src/modules/chapters/components/Form.vue
- client/src/sagas/chapters.sagas.ts
- client/src/store/chapters.store.ts
- includes/api/chapters.php
- lib/chapters_manager.php
> Add image to chapters

- client/src/lib/chapters.ts
- client/src/sagas/chapters.sagas.ts
Bei Import/Export der Chapters wurde das Image noch nicht beachtet, ausserdem wurde beim Export der Chapters die Startzeit nicht beachtet, falls sie 0 ist.
> chore: Import/Export add image chapters

- client/src/modules/transcripts/components/Import.vue
- client/src/sagas/transcripts.sagas.ts
- client/src/store/transcripts.store.ts
- lib/modules/transcripts/rest_api.php
- lib/modules/transcripts/transcripts.php
Das Transcript kann jetzt auch aus den Assets importiert werden.
> fix(transcripts) #1295 Add transcript from asset

- Makefile
- bin/uadetect.php
- composer.json
- composer.lock
- config/php-scoper/piwik.inc.php
- config/php-scoper/twig.inc.php
- lib/model/user_agent.php
fixes https://github.com/podlove/podlove-publisher/issues/1206
> feat: vendor-prefix piwik/device-detector

- includes/api/episodes.php
- lib/modules/contributors/rest_api.php
Hello Eric,
the user can set the slug with the RestAPI, but I don't create MediaFile entries. I added also two small points
1. Set the duration
2. Get the episode publihsDate
Dirk
> Rest API - episode set slug

- includes/api/episodes.php
Make recording date of an episode read- and writeable using the REST API.
> Expose recording date of episode to REST API

- includes/api/episodes.php
Added a new route
podlove/v2/episodes/{id}/media
> chore(api): add media file endpoint (#1313)

- includes/api/episodes.php
- includes/api/episodes/related_episodes.php
- lib/api/error.php
- lib/modules/related_episodes/related_episodes.php
1. Ich habe die fehlenden Einträge license_name und license_url zur Episode-Route hinzugefügt.
2. Ich habe einen API-Endpunkt für die related Episode erzeugt.
> Add data to API  see #1328 und #1339

- client/src/sagas/episode.sagas.ts
> fix: collect episodes update

- client/index.html
- client/src/modules/index.ts
- client/src/modules/soundbite/Soundbite.vue
- client/src/modules/soundbite/components/Clear.vue
- client/src/modules/soundbite/components/Form.vue
- client/src/modules/soundbite/index.ts
- client/src/store/episode.store.ts
- client/src/store/selectors.ts
- lib/modules/soundbite/soundbite.php
This commit solved the #1346 issue.
> feat(episode ui) - Move soundbite ui to new ui approach

- client/src/modules/contributors/components/AddContribution.vue
Disclaimer: Potential fix, I can't reproduce it locally. Might interfere with a global popper instance
> fix: Contributors Combobox does not open correctly #1380

- lib/feeds/base.php
- lib/settings/podcast/tab/directory.php
> Adding multi-category support

- lib/modules/contributors/contributors.php
add missing property (position)
> fix(contributor) - solve #1413

- includes/api/episodes.php
- includes/db_migration.php
- lib/model/media_file.php
- lib/version.php
- plugin.php
- closes https://github.com/podlove/podlove-publisher/issues/1274
- fixes https://github.com/podlove/podlove-publisher/issues/1410
TODO
> Never delete media files

- client/src/modules/index.ts
- client/src/modules/shows/ShowSelect.vue
- client/src/modules/shows/index.ts
- client/src/sagas/shows.sagas.ts
- client/src/store/episode.store.ts
- client/src/store/index.ts
- client/src/store/reducers.ts
- client/src/store/selectors.ts
- client/src/store/shows.store.ts
- client/src/types/shows.types.ts
- includes/api/episodes.php
- lib/ajax/ajax.php
- lib/model/episode.php
- lib/modules/automatic_numbering/automatic_numbering.php
- lib/modules/shows/rest_api.php
- lib/modules/shows/shows.php
- add shows selection vue component
- show selection is now compatible with automatic numbering again
- remove old code
> feat: vueify shows selection

- client/src/modules/index.ts
Sorry! Den Punkt habe ich im CodeReview leider übersehen.
> Onboarding is moved to publisher-next

- includes/api/podcast.php
Für den Onboarding Assistanten wird die Speicherung des Covers und der Sprache des Podcasts benötigt.
> chore: podcast api add missing items (language, cover_image)

- client/src/lib/api.ts
- client/src/lib/auphonic.api.ts
- client/src/modules/auphonic/components/FileChooser.vue
- client/src/modules/auphonic/components/ManageProductionForm.vue
- client/src/sagas/auphonic.sagas.ts
- client/src/store/index.ts
- client/src/store/progress.store.ts
- client/src/store/reducers.ts
- client/src/store/selectors.ts
Show file upload progress. Screenshot shows single track, but works for multi track too. Reworked the whole upload UI too for consistency.
> Feature: Auphonic Upload Progress

- includes/api/episodes.php
- includes/downloads.php
- includes/images.php
- lib/api/error.php
- lib/model/download_intent.php
- lib/model/image.php
- lib/model/user_agent.php
- lib/modules/oembed/oembed.php
- lib/modules/plus/plus.php
- lib/modules/transcripts/renderer.php
Fixes various small issues (notices, warnings, errors)
based on #1534
> Various small fixes

- lib/modules/onboarding/rest_api.php
> fix(onboarding) - #1533 Don't overwrite user settings
